# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 39fff1f6952d13e01cfbac04a880098c365a90d9766f84d983b6b347c95dea84267a9b7670d33798db33f2a4ca9336de891de3e1e8155319eb71b97b0cfbe378

test:
  secret_key_base: c8865f53604c2bb8210d31d75b72001b37b460d75362f7ef9a90107d1ce28e202465a9e81a10a772b4c17d4375138de66be4b1927212cf57be5c2363aa6e7f7b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
